export enum EnumEnvironment {
  DEVELOPMENT = "DEVELOPMENT",
  PRODUCTION = "PRODUCTION",
}

export enum TokenTypes {
  ACCESS_TOKEN = "ACCESS_TOKEN",
  REFRESH_TOKEN = "REFRESH_TOKEN",
  VERIFY_EMAIL_TOKEN = "VERIFY_EMAIL_TOKEN",
}

export enum UserAuthMethod {
  EMAIL_PASSWORD = "EMAIL_PASSWORD",
  BIOMETRIC = "BIOMETRIC",
  FACEBOOK = "FACEBOOK",
  GOOGLE = "GOOGLE",
  GITHUB = "GITHUB",
  APPLE = "APPLE",
}

export enum UserStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED", // User temporarily locked
  DEACTIVATED = "DEACTIVATED",
}
